language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
script:
# Unit Test & Integration Test
- mvn verify
# Calidad codigo: Sonarcloud
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR
